# Comment that will be sent if an issue is judged to be closed
comment: "This issue is closed because it does not meet our issue template. Please read it. \n您好，我是问题处理机器人，因为您没有按规定提交问题，所以被我自动关闭了。"
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# Example 1: bug report
  - "Expected Behavior"
  - "Current Behavior"
  - "Steps to Reproduce"
  - "Detailed Description"
- content:
# Example 2: feature request
  - "Motivation / Use Case"
  - "Expected Behavior"
  - "Other Information"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.